# Generated by Django 5.0.6 on 2024-05-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
