# Generated by Django 5.0.6 on 2024-06-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_subject_studentmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentMarks',
            new_name='SubjectMarks',
        ),
    ]
