# Generated by Django 5.0.6 on 2024-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_rename_studentmarks_subjectmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'student'},
        ),
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
