# Generated by Django 5.0.6 on 2024-06-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_alter_student_options_alter_studentid_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmarks',
            options={'ordering': ['student']},
        ),
    ]
